### ISSUE TITLE
[ZF2] Statement could not be executed with paginator and view

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-db#130] opened 2020-01-16 19:32 UTC
Hi,

When i use a view with a paginator the where->like with sql\expression doesn't work with the message :

Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIKE '%aa%') AS original_select' at line 1)

The code :
`$select->where->like(new \Zend\Db\Sql\Predicate\Expression("concat(nom,' ',prenom)"), '%' . $value . "%");`

Actually to solve this pb, i do the concatenation in my view.

Regards,

PYT

---

Originally posted by @Payalba at https://github.com/zendframework/zend-db/issues/90

**Comment by samsonasik** [comment] 2020-08-10 03:15
I tried it and I can't reproduce in latest laminas-db: 

![Screen Shot 2020-08-10 at 10 13 27 AM](https://user-images.githubusercontent.com/459648/89749500-31c29d00-daf2-11ea-922c-acbfd40e90b0.png)

I am closing it.

**Closed by samsonasik** 2020-08-10 03:15 UTC
