### ISSUE TITLE
Documentation code blocks

### ISSUE THREAD

**Issue by lpj145** [laminas/laminas-db#38] opened 2020-01-04 00:49 UTC
When i read the docs i found some unstyled code blocks and this turn codes unreadable, please consider two things.
![image](https://user-images.githubusercontent.com/11980109/71757209-d8670100-2e72-11ea-8a1c-3968415f5fe4.png)

i make some change, if you can change this.
![image](https://user-images.githubusercontent.com/11980109/71757199-ca18e500-2e72-11ea-94f7-969bf17ee86d.png)
![image](https://user-images.githubusercontent.com/11980109/71757203-d13ff300-2e72-11ea-9f96-a4bb815ab0ce.png)

**Comment by lpj145** [comment] 2020-01-04 00:49
i think is so simple to change.

**Comment by froschdesign** [comment] 2020-01-04 07:32
It's a [different problem](https://github.com/laminas/documentation-theme/issues/3#issuecomment-570651587) and we already work on this.

For laminas-db it is fixed, all other documentations will follow.

> i think is so simple to change.

Sadly not because it is not a CSS problem, the coloured code is missing and we have to change all repositories.

---

Duplicate of https://github.com/laminas/documentation-theme/issues/3

**Closed by froschdesign** 2020-01-04 07:32 UTC
